# Generated by Django 4.2.3 on 2023-07-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("favmusics", "0002_alter_music_options_customer_profile_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="profile_image",
            field=models.ImageField(null=True, upload_to="profile_images/"),
        ),
    ]
