# Generated by Django 4.2.3 on 2023-07-21 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("favmusics", "0004_music_date_added_music_remarks"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClaimLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("claim_number", models.CharField(max_length=50)),
                ("claim_amount", models.FloatField()),
                ("cpt_code", models.CharField(max_length=30)),
                ("client_partition", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ParsedClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("claim_number", models.CharField(max_length=50)),
                ("claim_amount", models.FloatField()),
                ("cpt_code", models.CharField(max_length=30)),
                ("client_partition", models.CharField(max_length=50)),
                ("edi_payer_id", models.CharField(max_length=30)),
                ("service_line", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Payer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("edi_payer_id", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="ServiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_line", models.CharField(max_length=30)),
                (
                    "claims_line_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="favmusics.claimline",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="claimline",
            name="payer_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="favmusics.payer"
            ),
        ),
    ]
