# Generated by Django 4.2.3 on 2023-07-21 19:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("favmusics", "0005_claimline_parsedclaim_payer_serviceline_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="claimline",
            unique_together={("claim_number", "client_partition")},
        ),
    ]
